version: "3.8"
services:
  monitor_bot:
    build: .
    restart: always
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - PROC_PATH=/host/proc
